### ISSUE TITLE
Typo in dice_loss method

### ISSUE THREAD

**Issue by AnshumaanDash** [kevinzakka/pytorch-goodies#2]
Hi,
Thanks for the awesome repository.

I happened to notice the following typo in the ```dice_loss``` method in ```losses.py```

```line 84: probas = F.softmax(probas, dim=1)``` 

It should be ```probas = F.softmax(logits, dim=1)```

Kindly make the change.
Thanks

**Comment by kevinzakka** [comment]
@AnshumaanDash thanks for the heads-up, I had that fixed locally (along with a GPU fix) but never pushed them. Should be good to go now!
